// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Svac.AdminHost.Domain.Persistence;

#nullable disable

namespace Svac.AdminHost.Domain.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260712030839_InitialAdmin")]
    partial class InitialAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Svac.AdminHost.Domain.Persistence.StaffAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_subject");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_accounts_email");

                    b.HasIndex("ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_accounts_external_subject");

                    b.ToTable("staff_accounts", "admin", t =>
                        {
                            t.HasCheckConstraint("ck_staff_accounts_status", "status IN ('active','deactivated')");
                        });
                });

            modelBuilder.Entity("Svac.AdminHost.Domain.Persistence.StaffRoleGrantEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("GrantReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grant_reason");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("granted_by");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("text")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_id");

                    b.HasKey("Id");

                    b.HasIndex("StaffId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_active_grant")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("staff_role_grants", "admin", t =>
                        {
                            t.HasCheckConstraint("ck_staff_role_grants_role", "role IN ('super_admin','safety_agent','content_moderator','venue_con_ops','economy_ops','analyst')");
                        });
                });

            modelBuilder.Entity("Svac.AdminHost.Domain.Persistence.StaffRoleGrantEntity", b =>
                {
                    b.HasOne("Svac.AdminHost.Domain.Persistence.StaffAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
