// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Svac.DomainCore.Persistence;

#nullable disable

namespace Svac.DomainCore.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Svac.DomainCore.Persistence.ConfigEntryEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("BoundsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("bounds");

                    b.Property<string>("Gate")
                        .HasColumnType("text")
                        .HasColumnName("gate");

                    b.Property<bool>("RequiresReason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_reason");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("config_entries", "core", t =>
                        {
                            t.HasCheckConstraint("ck_config_entries_scope", "scope IN ('founder','ops','set')");
                        });
                });

            modelBuilder.Entity("Svac.DomainCore.Persistence.DataProtectionKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml_data");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", "core");
                });

            modelBuilder.Entity("Svac.DomainCore.Persistence.FieldKeyRefEntity", b =>
                {
                    b.Property<string>("FieldKeyId")
                        .HasColumnType("text")
                        .HasColumnName("field_key_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<string>("VaultKeyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vault_key_name");

                    b.HasKey("FieldKeyId");

                    b.ToTable("field_key_refs", "core");
                });

            modelBuilder.Entity("Svac.DomainCore.Persistence.LedgerBalanceEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<long>("Points")
                        .HasColumnType("bigint")
                        .HasColumnName("points");

                    b.Property<long>("Svac")
                        .HasColumnType("bigint")
                        .HasColumnName("svac");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Watermark")
                        .HasColumnType("bigint")
                        .HasColumnName("watermark");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("UserId");

                    b.ToTable("ledger_balances", "core");
                });

            modelBuilder.Entity("Svac.DomainCore.Persistence.LedgerEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CrewId")
                        .HasColumnType("text")
                        .HasColumnName("crew_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("EvidenceRef")
                        .HasColumnType("text")
                        .HasColumnName("evidence_ref");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("QuestId")
                        .HasColumnType("text")
                        .HasColumnName("quest_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ReversalOf")
                        .HasColumnType("text")
                        .HasColumnName("reversal_of");

                    b.Property<long>("Svac")
                        .HasColumnType("bigint")
                        .HasColumnName("svac");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("ReversalOf");

                    b.ToTable("ledger_entries", "core", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_points_nonneg", "points >= 0");

                            t.HasCheckConstraint("ck_ledger_entries_xp_eq_points", "xp = points");
                        });
                });

            modelBuilder.Entity("Svac.DomainCore.Persistence.ProjectionCheckpointEntity", b =>
                {
                    b.Property<string>("ConsumerId")
                        .HasColumnType("text")
                        .HasColumnName("consumer_id");

                    b.Property<string>("StreamType")
                        .HasColumnType("text")
                        .HasColumnName("stream_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WatermarkSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("watermark_seq");

                    b.HasKey("ConsumerId", "StreamType");

                    b.ToTable("projection_checkpoints", "core");
                });

            modelBuilder.Entity("Svac.DomainCore.Persistence.PurgeRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("PurgeClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purge_class");

                    b.Property<int>("RowsAffected")
                        .HasColumnType("integer")
                        .HasColumnName("rows_affected");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StoreKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_key");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_ref");

                    b.HasKey("Id");

                    b.ToTable("purge_runs", "core");
                });

            modelBuilder.Entity("Svac.DomainCore.Persistence.QuotaCounterEntity", b =>
                {
                    b.Property<string>("ActorRef")
                        .HasColumnType("text")
                        .HasColumnName("actor_ref");

                    b.Property<string>("QuotaKey")
                        .HasColumnType("text")
                        .HasColumnName("quota_key");

                    b.Property<string>("WindowKey")
                        .HasColumnType("text")
                        .HasColumnName("window_key");

                    b.Property<int>("Consumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consumed");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ActorRef", "QuotaKey", "WindowKey");

                    b.ToTable("quota_counters", "core");
                });

            modelBuilder.Entity("events_audit", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_ref");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<long>("GlobalSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("global_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GlobalSeq"));

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ReversalOf")
                        .HasColumnType("text")
                        .HasColumnName("reversal_of");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_id");

                    b.Property<bool>("Tombstone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tombstone");

                    b.HasKey("EventId");

                    b.HasIndex("GlobalSeq");

                    b.HasIndex("ReversalOf");

                    b.HasIndex("ActorRef", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_events_audit_actor_ref_recorded_at");

                    b.HasIndex("EventType", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_events_audit_event_type_recorded_at");

                    b.HasIndex("StreamId", "Seq")
                        .IsUnique();

                    b.ToTable("events_audit", "core", t =>
                        {
                            t.HasCheckConstraint("ck_events_audit_payload_null_iff_tombstoned", "NOT tombstone OR payload IS NULL");
                        });
                });

            modelBuilder.Entity("events_behavioral", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_ref");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<long>("GlobalSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("global_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GlobalSeq"));

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ReversalOf")
                        .HasColumnType("text")
                        .HasColumnName("reversal_of");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_id");

                    b.Property<bool>("Tombstone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tombstone");

                    b.HasKey("EventId");

                    b.HasIndex("GlobalSeq");

                    b.HasIndex("ReversalOf");

                    b.HasIndex("StreamId", "Seq")
                        .IsUnique();

                    b.ToTable("events_behavioral", "core", t =>
                        {
                            t.HasCheckConstraint("ck_events_behavioral_payload_null_iff_tombstoned", "NOT tombstone OR payload IS NULL");
                        });
                });

            modelBuilder.Entity("events_consent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_ref");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<long>("GlobalSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("global_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GlobalSeq"));

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ReversalOf")
                        .HasColumnType("text")
                        .HasColumnName("reversal_of");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_id");

                    b.Property<bool>("Tombstone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tombstone");

                    b.HasKey("EventId");

                    b.HasIndex("GlobalSeq");

                    b.HasIndex("ReversalOf");

                    b.HasIndex("StreamId", "Seq")
                        .IsUnique();

                    b.ToTable("events_consent", "core", t =>
                        {
                            t.HasCheckConstraint("ck_events_consent_payload_null_iff_tombstoned", "NOT tombstone OR payload IS NULL");
                        });
                });

            modelBuilder.Entity("events_heatmap_provenance", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_ref");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<long>("GlobalSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("global_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GlobalSeq"));

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ReversalOf")
                        .HasColumnType("text")
                        .HasColumnName("reversal_of");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_id");

                    b.Property<bool>("Tombstone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tombstone");

                    b.HasKey("EventId");

                    b.HasIndex("GlobalSeq");

                    b.HasIndex("ReversalOf");

                    b.HasIndex("StreamId", "Seq")
                        .IsUnique();

                    b.ToTable("events_heatmap_provenance", "core", t =>
                        {
                            t.HasCheckConstraint("ck_events_heatmap_provenance_payload_null_iff_tombstoned", "NOT tombstone OR payload IS NULL");
                        });
                });

            modelBuilder.Entity("events_ledger", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_ref");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<long>("GlobalSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("global_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GlobalSeq"));

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ReversalOf")
                        .HasColumnType("text")
                        .HasColumnName("reversal_of");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_id");

                    b.Property<bool>("Tombstone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tombstone");

                    b.HasKey("EventId");

                    b.HasIndex("GlobalSeq");

                    b.HasIndex("ReversalOf");

                    b.HasIndex("StreamId", "Seq")
                        .IsUnique();

                    b.ToTable("events_ledger", "core", t =>
                        {
                            t.HasCheckConstraint("ck_events_ledger_payload_null_iff_tombstoned", "NOT tombstone OR payload IS NULL");
                        });
                });

            modelBuilder.Entity("events_reputation", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_ref");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<long>("GlobalSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("global_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GlobalSeq"));

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ReversalOf")
                        .HasColumnType("text")
                        .HasColumnName("reversal_of");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_id");

                    b.Property<bool>("Tombstone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tombstone");

                    b.HasKey("EventId");

                    b.HasIndex("GlobalSeq");

                    b.HasIndex("ReversalOf");

                    b.HasIndex("StreamId", "Seq")
                        .IsUnique();

                    b.ToTable("events_reputation", "core", t =>
                        {
                            t.HasCheckConstraint("ck_events_reputation_payload_null_iff_tombstoned", "NOT tombstone OR payload IS NULL");
                        });
                });

            modelBuilder.Entity("Svac.DomainCore.Persistence.LedgerEntryEntity", b =>
                {
                    b.HasOne("Svac.DomainCore.Persistence.LedgerEntryEntity", null)
                        .WithMany()
                        .HasForeignKey("ReversalOf")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
