CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
            CREATE SCHEMA core;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.config_entries (
        key text NOT NULL,
        type text NOT NULL,
        value jsonb NOT NULL,
        scope text NOT NULL,
        gate text,
        bounds jsonb,
        requires_reason boolean NOT NULL DEFAULT FALSE,
        updated_at timestamp with time zone NOT NULL,
        updated_by text NOT NULL,
        CONSTRAINT "PK_config_entries" PRIMARY KEY (key),
        CONSTRAINT ck_config_entries_scope CHECK (scope IN ('founder','ops','set'))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.data_protection_keys (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        friendly_name text,
        xml_data text,
        CONSTRAINT "PK_data_protection_keys" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.events_audit (
        event_id text NOT NULL,
        stream_id text NOT NULL,
        seq bigint NOT NULL,
        event_type text NOT NULL,
        payload jsonb,
        reversal_of text,
        tombstone boolean NOT NULL DEFAULT FALSE,
        actor_ref text NOT NULL,
        region text NOT NULL,
        lawful_basis text NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        recorded_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_events_audit" PRIMARY KEY (event_id),
        CONSTRAINT ck_events_audit_payload_null_iff_tombstoned CHECK (NOT tombstone OR payload IS NULL)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.events_behavioral (
        event_id text NOT NULL,
        stream_id text NOT NULL,
        seq bigint NOT NULL,
        event_type text NOT NULL,
        payload jsonb,
        reversal_of text,
        tombstone boolean NOT NULL DEFAULT FALSE,
        actor_ref text NOT NULL,
        region text NOT NULL,
        lawful_basis text NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        recorded_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_events_behavioral" PRIMARY KEY (event_id),
        CONSTRAINT ck_events_behavioral_payload_null_iff_tombstoned CHECK (NOT tombstone OR payload IS NULL)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.events_consent (
        event_id text NOT NULL,
        stream_id text NOT NULL,
        seq bigint NOT NULL,
        event_type text NOT NULL,
        payload jsonb,
        reversal_of text,
        tombstone boolean NOT NULL DEFAULT FALSE,
        actor_ref text NOT NULL,
        region text NOT NULL,
        lawful_basis text NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        recorded_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_events_consent" PRIMARY KEY (event_id),
        CONSTRAINT ck_events_consent_payload_null_iff_tombstoned CHECK (NOT tombstone OR payload IS NULL)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.events_heatmap_provenance (
        event_id text NOT NULL,
        stream_id text NOT NULL,
        seq bigint NOT NULL,
        event_type text NOT NULL,
        payload jsonb,
        reversal_of text,
        tombstone boolean NOT NULL DEFAULT FALSE,
        actor_ref text NOT NULL,
        region text NOT NULL,
        lawful_basis text NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        recorded_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_events_heatmap_provenance" PRIMARY KEY (event_id),
        CONSTRAINT ck_events_heatmap_provenance_payload_null_iff_tombstoned CHECK (NOT tombstone OR payload IS NULL)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.events_ledger (
        event_id text NOT NULL,
        stream_id text NOT NULL,
        seq bigint NOT NULL,
        event_type text NOT NULL,
        payload jsonb,
        reversal_of text,
        tombstone boolean NOT NULL DEFAULT FALSE,
        actor_ref text NOT NULL,
        region text NOT NULL,
        lawful_basis text NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        recorded_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_events_ledger" PRIMARY KEY (event_id),
        CONSTRAINT ck_events_ledger_payload_null_iff_tombstoned CHECK (NOT tombstone OR payload IS NULL)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.events_reputation (
        event_id text NOT NULL,
        stream_id text NOT NULL,
        seq bigint NOT NULL,
        event_type text NOT NULL,
        payload jsonb,
        reversal_of text,
        tombstone boolean NOT NULL DEFAULT FALSE,
        actor_ref text NOT NULL,
        region text NOT NULL,
        lawful_basis text NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        recorded_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_events_reputation" PRIMARY KEY (event_id),
        CONSTRAINT ck_events_reputation_payload_null_iff_tombstoned CHECK (NOT tombstone OR payload IS NULL)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.field_key_refs (
        field_key_id text NOT NULL,
        vault_key_name text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        retired_at timestamp with time zone,
        CONSTRAINT "PK_field_key_refs" PRIMARY KEY (field_key_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.ledger_balances (
        user_id text NOT NULL,
        points bigint NOT NULL,
        xp bigint NOT NULL,
        svac bigint NOT NULL,
        watermark bigint NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ledger_balances" PRIMARY KEY (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.ledger_entries (
        id text NOT NULL,
        user_id text NOT NULL,
        crew_id text,
        event_type text NOT NULL,
        points integer NOT NULL,
        xp integer NOT NULL,
        svac bigint NOT NULL,
        quest_id text,
        evidence_ref text,
        region text NOT NULL,
        lawful_basis text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        reversal_of text,
        CONSTRAINT "PK_ledger_entries" PRIMARY KEY (id),
        CONSTRAINT ck_ledger_entries_points_nonneg CHECK (points >= 0),
        CONSTRAINT ck_ledger_entries_xp_eq_points CHECK (xp = points),
        CONSTRAINT "FK_ledger_entries_ledger_entries_reversal_of" FOREIGN KEY (reversal_of) REFERENCES core.ledger_entries (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.projection_checkpoints (
        consumer_id text NOT NULL,
        stream_type text NOT NULL,
        watermark_seq bigint NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_projection_checkpoints" PRIMARY KEY (consumer_id, stream_type)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.purge_runs (
        id text NOT NULL,
        purge_class text NOT NULL,
        subject_ref text NOT NULL,
        store_key text NOT NULL,
        rows_affected integer NOT NULL,
        started_at timestamp with time zone NOT NULL,
        completed_at timestamp with time zone,
        evidence jsonb,
        CONSTRAINT "PK_purge_runs" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE TABLE core.quota_counters (
        actor_ref text NOT NULL,
        quota_key text NOT NULL,
        window_key text NOT NULL,
        consumed integer NOT NULL DEFAULT 0,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_quota_counters" PRIMARY KEY (actor_ref, quota_key, window_key)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE INDEX "IX_events_audit_reversal_of" ON core.events_audit (reversal_of);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_events_audit_stream_id_seq" ON core.events_audit (stream_id, seq);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE INDEX "IX_events_behavioral_reversal_of" ON core.events_behavioral (reversal_of);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_events_behavioral_stream_id_seq" ON core.events_behavioral (stream_id, seq);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE INDEX "IX_events_consent_reversal_of" ON core.events_consent (reversal_of);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_events_consent_stream_id_seq" ON core.events_consent (stream_id, seq);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE INDEX "IX_events_heatmap_provenance_reversal_of" ON core.events_heatmap_provenance (reversal_of);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_events_heatmap_provenance_stream_id_seq" ON core.events_heatmap_provenance (stream_id, seq);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE INDEX "IX_events_ledger_reversal_of" ON core.events_ledger (reversal_of);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_events_ledger_stream_id_seq" ON core.events_ledger (stream_id, seq);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE INDEX "IX_events_reputation_reversal_of" ON core.events_reputation (reversal_of);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_events_reputation_stream_id_seq" ON core.events_reputation (stream_id, seq);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE INDEX "IX_ledger_entries_reversal_of" ON core.ledger_entries (reversal_of);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    ALTER TABLE core.events_ledger
        ADD CONSTRAINT fk_events_ledger_reversal_of
        FOREIGN KEY (reversal_of) REFERENCES core.events_ledger(event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    ALTER TABLE core.events_reputation
        ADD CONSTRAINT fk_events_reputation_reversal_of
        FOREIGN KEY (reversal_of) REFERENCES core.events_reputation(event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    ALTER TABLE core.events_consent
        ADD CONSTRAINT fk_events_consent_reversal_of
        FOREIGN KEY (reversal_of) REFERENCES core.events_consent(event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    ALTER TABLE core.events_behavioral
        ADD CONSTRAINT fk_events_behavioral_reversal_of
        FOREIGN KEY (reversal_of) REFERENCES core.events_behavioral(event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    ALTER TABLE core.events_audit
        ADD CONSTRAINT fk_events_audit_reversal_of
        FOREIGN KEY (reversal_of) REFERENCES core.events_audit(event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    ALTER TABLE core.events_heatmap_provenance
        ADD CONSTRAINT fk_events_heatmap_provenance_reversal_of
        FOREIGN KEY (reversal_of) REFERENCES core.events_heatmap_provenance(event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE OR REPLACE FUNCTION core.enforce_append_only() RETURNS trigger AS $$
    BEGIN
        IF (TG_OP = 'DELETE') THEN
            IF (current_setting('core.purge_delete_authorized', true) IS DISTINCT FROM 'on') THEN
                RAISE EXCEPTION 'core.%: DELETE is never permitted on an append-only table outside the purge-pipeline session-local carve-out (SLICE_S1_CONTRACT.md §2/§6)', TG_TABLE_NAME;
            END IF;
            -- authorized: the ONE caller (PurgePipeline) sets this session-local GUC via
            -- SET LOCAL, inside its own transaction, immediately before this statement —
            -- never reachable from any application/consumer write path.
        ELSIF (TG_OP = 'UPDATE') THEN
            IF (OLD.tombstone = true) THEN
                RAISE EXCEPTION 'core.%: row % is already tombstoned — no further mutation is sanctioned', TG_TABLE_NAME, OLD.event_id;
            ELSIF (NEW.tombstone = true AND NEW.payload IS NULL
                   AND NEW.actor_ref IS NOT DISTINCT FROM OLD.actor_ref) THEN
                NULL; -- the tombstone transition: permitted.
            ELSIF (NEW.tombstone IS DISTINCT FROM true
                   AND NEW.payload IS NOT DISTINCT FROM OLD.payload
                   AND NEW.actor_ref IS DISTINCT FROM OLD.actor_ref
                   AND NEW.event_id IS NOT DISTINCT FROM OLD.event_id
                   AND NEW.stream_id IS NOT DISTINCT FROM OLD.stream_id
                   AND NEW.seq IS NOT DISTINCT FROM OLD.seq
                   AND NEW.event_type IS NOT DISTINCT FROM OLD.event_type
                   AND NEW.reversal_of IS NOT DISTINCT FROM OLD.reversal_of
                   AND NEW.region IS NOT DISTINCT FROM OLD.region
                   AND NEW.lawful_basis IS NOT DISTINCT FROM OLD.lawful_basis
                   AND NEW.occurred_at IS NOT DISTINCT FROM OLD.occurred_at
                   AND NEW.recorded_at IS NOT DISTINCT FROM OLD.recorded_at) THEN
                NULL; -- the pseudonymize transition: only actor_ref changes, permitted.
            ELSE
                RAISE EXCEPTION 'core.%: UPDATE permits only the (tombstone=false->true, payload->NULL) transition or the (actor_ref re-key) pseudonymize transition, no other column change (SLICE_S1_CONTRACT.md §2/§6)', TG_TABLE_NAME;
            END IF;
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE CONSTRAINT TRIGGER trg_events_ledger_append_only
        AFTER UPDATE OR DELETE ON core.events_ledger
        FOR EACH ROW EXECUTE FUNCTION core.enforce_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE CONSTRAINT TRIGGER trg_events_reputation_append_only
        AFTER UPDATE OR DELETE ON core.events_reputation
        FOR EACH ROW EXECUTE FUNCTION core.enforce_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE CONSTRAINT TRIGGER trg_events_consent_append_only
        AFTER UPDATE OR DELETE ON core.events_consent
        FOR EACH ROW EXECUTE FUNCTION core.enforce_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE CONSTRAINT TRIGGER trg_events_behavioral_append_only
        AFTER UPDATE OR DELETE ON core.events_behavioral
        FOR EACH ROW EXECUTE FUNCTION core.enforce_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE CONSTRAINT TRIGGER trg_events_audit_append_only
        AFTER UPDATE OR DELETE ON core.events_audit
        FOR EACH ROW EXECUTE FUNCTION core.enforce_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE CONSTRAINT TRIGGER trg_events_heatmap_provenance_append_only
        AFTER UPDATE OR DELETE ON core.events_heatmap_provenance
        FOR EACH ROW EXECUTE FUNCTION core.enforce_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE OR REPLACE FUNCTION core.enforce_ledger_append_only() RETURNS trigger AS $$
    BEGIN
        IF (TG_OP = 'DELETE') THEN
            RAISE EXCEPTION 'core.ledger_entries: DELETE is never permitted — reversal is the ONLY correction verb (SLICE_S1_CONTRACT.md §1b)';
        ELSIF (TG_OP = 'UPDATE') THEN
            IF (OLD.user_id = 'usr_REDACTED0000000000000000000') THEN
                RAISE EXCEPTION 'core.ledger_entries: row % user_id is already severed — the ONE sanctioned update path may run once', OLD.id;
            ELSIF (NEW.user_id IS DISTINCT FROM 'usr_REDACTED0000000000000000000'
                   OR NEW.crew_id IS DISTINCT FROM OLD.crew_id
                   OR NEW.event_type IS DISTINCT FROM OLD.event_type
                   OR NEW.points IS DISTINCT FROM OLD.points
                   OR NEW.xp IS DISTINCT FROM OLD.xp
                   OR NEW.svac IS DISTINCT FROM OLD.svac
                   OR NEW.quest_id IS DISTINCT FROM OLD.quest_id
                   OR NEW.evidence_ref IS DISTINCT FROM OLD.evidence_ref
                   OR NEW.region IS DISTINCT FROM OLD.region
                   OR NEW.lawful_basis IS DISTINCT FROM OLD.lawful_basis
                   OR NEW.created_at IS DISTINCT FROM OLD.created_at
                   OR NEW.reversal_of IS DISTINCT FROM OLD.reversal_of) THEN
                RAISE EXCEPTION 'core.ledger_entries: UPDATE permits only the user_id -> redacted-sentinel severing transition, every other column held fixed (SLICE_S1_CONTRACT.md §6)';
            END IF;
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    CREATE CONSTRAINT TRIGGER trg_ledger_entries_append_only
        AFTER UPDATE OR DELETE ON core.ledger_entries
        FOR EACH ROW EXECUTE FUNCTION core.enforce_ledger_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710085111_InitialCore') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260710085111_InitialCore', '10.0.9');
    END IF;
END $EF$;
COMMIT;

