// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Svac.Identity.Persistence;

#nullable disable

namespace Svac.Identity.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260711145012_InitialIdentity")]
    partial class InitialIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Svac.Identity.Persistence.AccountEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("account_state");

                    b.Property<DateTimeOffset>("AttestedAdultAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attested_adult_at");

                    b.Property<string>("AvatarRef")
                        .HasColumnType("text")
                        .HasColumnName("avatar_ref");

                    b.Property<byte[]>("BirthdateEnc")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("birthdate_enc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletionEffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_effective_at");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FandomTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fandom_tag");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<string>("IrlAccessState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("irl_access_state");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RegionSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_source");

                    b.Property<DateTimeOffset>("StateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_changed_at");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("terms_version");

                    b.Property<DateTimeOffset?>("TombstonedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tombstoned_at");

                    b.HasKey("AccountId");

                    b.HasIndex("DeletionEffectiveAt")
                        .HasDatabaseName("ix_accounts_deletion_due")
                        .HasFilter("deletion_effective_at IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_email")
                        .HasFilter("account_state <> 'deleted' AND email IS NOT NULL");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_handle")
                        .HasFilter("account_state <> 'deleted'");

                    b.ToTable("accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_accounts_state", "account_state IN ('active','suspended','banned','deleted')");
                        });
                });

            modelBuilder.Entity("Svac.Identity.Persistence.BanEvasionRefEntity", b =>
                {
                    b.Property<string>("HmacEmail")
                        .HasColumnType("text")
                        .HasColumnName("hmac_email");

                    b.Property<DateTimeOffset>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<byte[]>("PushTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("push_token_hash");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.HasKey("HmacEmail");

                    b.ToTable("ban_evasion_refs", "identity");
                });

            modelBuilder.Entity("Svac.Identity.Persistence.ConsentCurrentEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("ConsentKind")
                        .HasColumnType("text")
                        .HasColumnName("consent_kind");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surface");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("AccountId", "ConsentKind");

                    b.ToTable("consent_current", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_consent_current_status", "status IN ('granted','revoked')");
                        });
                });

            modelBuilder.Entity("Svac.Identity.Persistence.DeletionJobEntity", b =>
                {
                    b.Property<string>("DeletionId")
                        .HasColumnType("text")
                        .HasColumnName("deletion_id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("CustodyHoldRefsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("custody_hold_refs");

                    b.Property<int?>("CustodyHoldsFound")
                        .HasColumnType("integer")
                        .HasColumnName("custody_holds_found");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<bool>("ExportOffered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("export_offered");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("PurgeRunIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("purge_run_ids");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("DeletionId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_deletion_jobs_account");

                    b.ToTable("deletion_jobs", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_deletion_jobs_state", "state IN ('scheduled','canceled','executing','held','complete')");
                        });
                });

            modelBuilder.Entity("Svac.Identity.Persistence.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("PushToken")
                        .HasColumnType("text")
                        .HasColumnName("push_token");

                    b.Property<DateTimeOffset?>("PushTokenUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("push_token_updated_at");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("DeviceId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_devices_account")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("devices", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_devices_platform", "platform IN ('ios','android','web')");
                        });
                });

            modelBuilder.Entity("Svac.Identity.Persistence.EmailChallengeEntity", b =>
                {
                    b.Property<string>("ChallengeId")
                        .HasColumnType("text")
                        .HasColumnName("challenge_id");

                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailLower")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_lower");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<byte[]>("VerifiedTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("verified_token_hash");

                    b.HasKey("ChallengeId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_email_challenges_account");

                    b.HasIndex("EmailLower")
                        .HasDatabaseName("ix_email_challenges_email_lower");

                    b.ToTable("email_challenges", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_email_challenges_purpose", "purpose IN ('signup','login','email_change')");
                        });
                });

            modelBuilder.Entity("Svac.Identity.Persistence.ExportJobEntity", b =>
                {
                    b.Property<string>("ExportId")
                        .HasColumnType("text")
                        .HasColumnName("export_id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<byte[]>("Artifact")
                        .HasColumnType("bytea")
                        .HasColumnName("artifact");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("ExportId");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_export_active")
                        .HasFilter("state IN ('pending','ready')");

                    b.ToTable("export_jobs", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_export_jobs_state", "state IN ('pending','ready','delivered','expired','failed')");
                        });
                });

            modelBuilder.Entity("Svac.Identity.Persistence.HandleHistoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("NewHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_handle");

                    b.Property<string>("OldHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_handle");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_handle_history_account");

                    b.ToTable("handle_history", "identity");
                });

            modelBuilder.Entity("Svac.Identity.Persistence.PushCategoryConsentEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId", "Category");

                    b.ToTable("push_category_consents", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_push_category_consents_category", "category BETWEEN 1 AND 9 AND category <> 8");
                        });
                });

            modelBuilder.Entity("Svac.Identity.Persistence.RefreshTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("SupersededBy")
                        .HasColumnType("text")
                        .HasColumnName("superseded_by");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("Svac.Identity.Persistence.ReservedHandleEntity", b =>
                {
                    b.Property<string>("Handle")
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Handle");

                    b.ToTable("reserved_handles", "identity");
                });

            modelBuilder.Entity("Svac.Identity.Persistence.RetiredHandleEntity", b =>
                {
                    b.Property<string>("Handle")
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<DateTimeOffset>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.HasKey("Handle");

                    b.ToTable("retired_handles", "identity");
                });

            modelBuilder.Entity("Svac.Identity.Persistence.SessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_expires_at");

                    b.Property<byte[]>("AccessTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_hash");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lawful_basis");

                    b.Property<string>("RefreshFamilyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_family_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("text")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("SessionId");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_sessions_access_token_hash");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_sessions_account")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("sessions", "identity");
                });
#pragma warning restore 612, 618
        }
    }
}
